### ISSUE TITLE
git submodules not working while cloning with https rather than git ssh 

### ISSUE THREAD

**Issue by ayushnawal** [internetarchive/openlibrary#1834]
## Description
While using URL of https while cloning the OL github . The setup gets disturbed at step no. 17 while building the first image . although images built succesfully but on running docker-compose up , terminal get paused with error message : Import Error : No module named infogami . 

![screenshot from 2019-01-18 02-27-07](https://user-images.githubusercontent.com/36100944/51430303-553ba380-1c3f-11e9-8e5c-9c6523303526.png)

Errors while building the first image in step 17 :
![screenshot from 2019-01-18 02-48-11](https://user-images.githubusercontent.com/36100944/51430268-a4350900-1c3e-11e9-94ea-1c23f84b2974.png)

##expectation
git modules should be downloaded and synchronise simultaneously !

> Operating system?
Ubuntu 16.04 
Docker version 18.09.1

i don't have much idea of the codebase yet .. i am a new comer here and i am opening an issue here for the very first time !

## Stakeholders
@mekarpeles @cdrini @hornc

**Comment by tfmorris** [comment]
The other issue has some useful debugging information on it, including the configuration of the submodules with some of them using git:// URLs and others using https://.

Can you clone repos from Github via the git: protocol? ie do you have an account with SSH keys set up and any other necessary stuff? Can you clone those submodules by hand using the URLs that in the .gitsubmodules file?

We should probably just switch all the URLs to http: for the submodules. That may be enough to avoid problems like this.

**Comment by ayushnawal** [comment]
@mek @tfmorris @tabshaikh  i think atleast updating the installation instructions by adding a line to recommend new contributors to clone the OL repo using git ssh will do the work for now ! i think we were assuming it to be quite obvious but it might not be the same case for everyone out there !

**Comment by tfmorris** [comment]
All of my repos are cloned using the git protocol, not https, and they work fine. Can you please answer my questions above so that we can try to understand what the actual problem is? (Unless someone else has already figured out the root cause and can add it here).

**Comment by Batey96** [comment]
I have had same problem but below steps fixed the problem:
-make sure you have ssh keys setup for your github account
-Do a recursive clone when cloning ol through ssh(git clone --recurse-submodules)
finall:continue with the images building

**Comment by mekarpeles** [comment]
resolved in readme

**Comment by yash-gupta2000** [comment]
I'm still facing same issue even after following all steps.
@mekarpeles
