### ISSUE TITLE
Edit UI for Author Autocomplete Failure

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2130]
## Description
Editing certain editions throws error: `/opt/openlibrary/deploys/openlibrary/811fbbf/openlibrary/templates/books/author-autocomplete.html`: error in processing template: AttributeError: 'str' object has no attribute 'name' (falling back to default template)

## Relevant url?
https://openlibrary.org/books/OL22449759M/The_handmaid's_tale
https://openlibrary.org/books/OL20930937M/The_handmaid's_tale

## Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Version 74.0.3729.131 (Official Build) (64-bit)
- **Operating system?** Win 7 Pro

**Comment by mekarpeles** [comment]
cc: @hornc, it may be bad data, can you give us any info about how common this case is?

**Comment by cdrini** [comment]
Lots of weirdness here. This _isn't_ an orphan, but it's displayed as an orphan in the UI, and it has an `authors` field (despite not being an orphan).

**Comment by cdrini** [comment]
Actually all editions are supposed to have authors; my bad

**Comment by tfmorris** [comment]
> Actually all editions are supposed to have authors; my bad

That's contrary to my understanding. I thought the authors were only on works. 

If they're allowed on editions, which takes precedence between works and editions?

**Comment by hornc** [comment]
Editions can optionally have authors in their metadata, which is potentially useful, but currently the UI does not display any of them and work authors _always_ take precedence.

Having authors on editions is currently super helpful in fixing up editions without works, so stripping authors from editions is not something we can do now, but could be a goal for later, if we decide we want to simplify the data model.

Also, I think there are some cases in the current data where edition metadata might be more accurate in terms of multiple authors than at the work level. Identifying and fixing these is a potential data clean up task.

I'd prefer if we had more accurate author and contributor data on works and editions where appropriate because the data model allows for it, e.g. recognising translators or editors of much published works at the edition level. Unfortunately, the contributor and role fields are not really populated correctly in the current data, nor is the UI set up for displaying or editing the full range of possibilities.

**Comment by tfmorris** [comment]
I phrased that badly. 

> > Actually all editions are supposed to have authors; my bad
> 
> That's contrary to my understanding. I thought the authors were only on works.

I understand that the data model (and some of our data) supports authors on editions and I see the value in edition specific metadata, but what we need to avoid is having data that is displayed (or worse used for operations like merge, but not displayed) and which is not editable. That's a data quality black hole and a very unsatisfying user experience. 

If the current edition authors are *completely* hidden (except through the API) and the work authors take precedence (and are editable), that seems satisfactory, if not ideal.

If, on the other hand, edition authors are leaking out into view, but aren't editable, that seems bad.

Obviously, orphan editions are a special case, since we want them to have as much work metadata as possible that we can use to create a new work or associate them with the correct work.

**Comment by hornc** [comment]
The edition has a work that is a redirect: https://openlibrary.org/works/OL675783W.json
which has the author in an odd format

**Comment by hornc** [comment]
I corrected the redirect by adding the title and a correct format author field, and was then able to shift the editions to the correct work https://openlibrary.org/works/OL15836807W/The_Handmaid's_Tale using the UI. Looks like this was a data issue on https://openlibrary.org/works/OL675783W?m=history

**Comment by hornc** [comment]
I just ran into another problem importing caused by the same thing, a redirect with an invalid format author ... to answer the question on how many: there are apparently only **26** works (all redirects) with this problem.

Downloading the `redirects` dump from https://archive.org/download/ol_dump_2019-04-30/
```
grep '"author": "/authors/' ol_dump_redirects_2019-04-30.txt  | wc -l
```
26

```
/works/OL3142697W
/works/OL1130032W
/works/OL15436853W
/works/OL2899877W
/works/OL518261W
/works/OL362704W
/works/OL652558W
/works/OL14820W
/works/OL14985572W
/works/OL362671W
/works/OL40252W
/works/OL36861W
/works/OL1198574W
/works/OL476641W
/works/OL44994W
/works/OL97776W
/works/OL7943063W
/works/OL16200777W
/works/OL675783W
/works/OL362687W
/works/OL16313W
/works/OL20934W
/works/OL8721462W
/works/OL362694W
/works/OL462942W
/works/OL24166W
```

**Comment by hornc** [comment]
fixed those by reverting the redirect changes. They seem to have a lot of associated editions still. Looks like the original cause was me attempting to merge works by redirecting without tidying up all of the linked editions. :worried:

**Comment by seabelis** [comment]
@hornc These are still broken. Different issue? https://openlibrary.org/people/seabelis/lists/OL129155L/broken
