### ISSUE TITLE
Make longer sections of form collapsible/expandable

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2245]
### Is your feature request related to a problem? Please describe.
The tables of contents and descriptions can be pretty long, requiring a lot of scrolling. 

### Describe the solution you'd like
It would be nice if these could be minimized, at least in view mode, if not in edit mode.

**Comment by seabelis** [comment]
Resolved with new books page.

**Comment by BrittanyBunk** [comment]
This is not resolved. Only the description is collapsible, the table of contents is not.  See https://openlibrary.org/books/OL32246478M/Visions_of_Arcadia . It looks hard to read. I hope this gets reopened, as I can't be creating new issues for closed ones.
