### ISSUE TITLE
There is a mismatch of availability of a book in a carousel to its true status

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2616]
### Example:
https://openlibrary.org/books/OL26571490M/Flush
https://openlibrary.org/books/OL26571491M/A_haunted_house_and_other_short_stories
![image](https://user-images.githubusercontent.com/55302685/77956345-92111a80-7286-11ea-8a9b-e17431ff2ccd.png)

### Problem:
Works in carousel say 'read', but when clicked on says 'no ebook available'. The expected result should be a read button there.

### Solution:
Change the carousel to match the availability of the edition (as what shows on the editions page is the true status)

### Stakeholders
Users - this issue creates confusion and frustration for someone hoping to see a book only to find out it's not available.

**Comment by guyjeangilles** [comment]
@BrittanyBunk "Read" is now taking me to the Works pages. Is the same happening for you? If so can we close this issue?

**Comment by BrittanyBunk** [comment]
@guyjeangilles still happening. Like https://openlibrary.org/works/OL39416W/Virginia_Woolf to click on  https://openlibrary.org/books/OL1557874M/Women_fiction. In the carousel, it says 'read'. When clicking on it, it goes to the edition page, but says 'no ebook available'

**Comment by Loquen** [comment]
@BrittanyBunk I'm trying to understand the issue here, what is the expected result of clicking 'read'? Should we change the wording to something other than 'read' or does the button need to redirect to another page?

**Comment by BrittanyBunk** [comment]
@Loquen I apologize. I reworded it. Check out what I wrote :)

**Comment by Loquen** [comment]
@BrittanyBunk Much clearer! Thanks for clarifying. So the solution seems to be if a book has a borrowable edition display it instead of the editions not in the library. If a book has only issues that are not in the library we can change the wording of the button to 'Not In Library' or something while still directing users to the books detail page.

**Comment by BrittanyBunk** [comment]
I think you're referring more to another issue I created: #3248. You're specifying though - as what are in carousels are mostly works, so it should redirect to the most available edition - that is a good thought! What I'm referring to here is if a book is in a carousel, then its availability would need to match, no matter what it is. No ebook -> no ebook, read -> read, borrow -> borrow, etc.

**Comment by BrittanyBunk** [comment]
I found the reason why!
The button (read, borrow, etc.) link to a book in the IA, while the book covers connect to the Work page of the OL edition webpage of the button.

**Comment by mekarpeles** [comment]
Should be resolved now

**Comment by BrittanyBunk** [comment]
@mekarpeles this is still an issue as it's been brought up again in #4379. Please reopen, so there's no duplicates.
