### ISSUE TITLE
Orphaned editions throw IndexError

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4051]
Fixed in ~#4052~

### Evidence / Screenshot (if possible)
http://staging.openlibrary.org/books/OL21692921M?debug=true

<class 'IndexError'> at /books/OL21692921M
list index out of range
Python	/openlibrary/openlibrary/templates/type/edition/view.html in __template__, line 9
Web	GET http://staging.openlibrary.org/books/OL21692921M

![Screenshot 2020-11-09 at 15 43 19](https://user-images.githubusercontent.com/3709715/98555825-ad271c80-22a2-11eb-9b29-8d2655aad82d.png)

### Relevant url?

http://staging.openlibrary.org/books/OL21692921M/Catharisme?debug=true&edition=

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Updated description; this isn't a Python 3 specific issue

**Comment by cclauss** [comment]
Fixed in #4052

**Comment by cdrini** [comment]
Here's the code the edit pages use to create a "dummy" work (not committed to db) to normalize rendering:

https://github.com/internetarchive/openlibrary/blob/b586b90cbf2a546e68444d401c6bcb5727054a55/openlibrary/plugins/upstream/addbook.py#L738-L746

**Comment by cclauss** [comment]
Fixed in #4286

**Comment by seabelis** [comment]
Still a problem on some records. https://openlibrary.org/books/OL16161815M/History_of_Chinese_literature.?debug=true

**Comment by cdrini** [comment]
Created a separate issue for this, since the cause of the error is very different this time :+1: #5404
