### ISSUE TITLE
TypeError: '>' not supported between instances of 'Nothing' and 'int' (falling back to default template) 

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4603]
/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: TypeError: '>' not supported between instances of 'Nothing' and 'int' (falling back to default template)

### Relevant url?
https://openlibrary.org/books/OL4902724M/The_adventures_of_Tom_Sawyer_Tom_Sawyer_abroad
https://openlibrary.org/books/OL965969M/The_complete_Tom_Sawyer

### Steps to Reproduce

1. Go to ...either of the urls above.
2. Do ...see error.

* Actual: Error displayed.
* Expected: Edition record should be displayed.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?**  Version 88.0.4324.150 (Official Build) (x86_64)
- **Operating system?** Mac Big Sur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@seabelis

**Comment by Yashs911** [comment]
@seabelis I would like to work on this issue.

**Comment by Yashs911** [comment]
![image](https://user-images.githubusercontent.com/64412143/108164663-3908da00-7117-11eb-96a6-bb3518a038bf.png)

on https://dev.openlibrary.org/books/OL4902724M/The_adventures_of_Tom_Sawyer_Tom_Sawyer_abroad it shows No data available and when I try to add another edition I am getting this error:

![image](https://user-images.githubusercontent.com/64412143/108164753-6f465980-7117-11eb-9848-44fa633aea95.png)

**Comment by cclauss** [comment]
To reproduce locally...
```bash
export HOSTNAME=${HOSTNAME:-$HOST}
export COMPOSE_FILE="docker-compose.yml:docker-compose.override.yml"
docker-compose down && PYENV_VERSION=3.9.1 docker-compose up -d && docker-compose logs -f --tail=10
# Control-C to stop log viewing
docker exec -it openlibrary_web_1 /bin/bash

scripts/copydocs.py /books/OL4902724M  # HTTPError --> openlibrary.api.OLError
scripts/copydocs.py /books/OL965969M  # HTTPError --> openlibrary.api.OLError
```

**Comment by cclauss** [comment]
Fixed by @cdrini magic.  He will need to explain how he did it!

**Comment by cdrini** [comment]
:D So basically, we looked at the .json of the _work_, and saw this weirdness:

```yml
authors:
-   author: /authors/OL18319A
    type:
        key: /type/author_role
covers:
- 320832
created:
    type: /type/datetime
    value: '2009-10-28T02:31:02.045223'
key: /works/OL413150W
last_modified:
    type: /type/datetime
    value: '2020-10-11T09:13:03.556587'
latest_revision: 12
location: /works/OL18155333W
revision: 12
subjects:
- American Humorous stories
- Huckleberry Finn (Fictitious character)
- Tom Sawyer (Fictitious character)
- Fiction
- American Adventure stories
- American fiction (fictional works by one author)
- Sawyer, tom (fictitious character), fiction
- Boys
type:
    key: /type/redirect
```

If you missed it, _it's a redirect!_; but for some reason it has a bunch of work fields like author/subject :/ Looking at the history:

![image](https://user-images.githubusercontent.com/6251786/108278874-b3525200-7149-11eb-8095-45116b79fee2.png)

It looks like this was caused by ImportBot :/ Not sure if this is still an issue, but it's been happening as late as Oct 2020.

I edited the yml directly and converted it to a /type/work: https://openlibrary.org/works/OL413150W.yml?m=edit . That seemed to fix it. Leaving it to you @seabelis to determine what the best thing to do with the data is :/

**Comment by seabelis** [comment]
More examples:

- [ ] https://openlibrary.org/works/OL490919W/untitled?debug=true

**Comment by seabelis** [comment]
Possible this is caused by works being merged when they have associated editions? 

I ran into this situation when I was cleaning up Shakespeare. I did not get an error at that time, but I would go to an edition and it would appear to be associated with an incorrect work. But the work did not actually appear to have the edition as its child. When I gained the ability to revert merges, I reverted many merges of works that still had associated editions and they turned out to be the correct works of those weird editions. I think this is a result of not being able to move more than 50 editions at a time. Because these were bot merges, the fact that the works had 50+ went unnoticed, so 50 editions would be migrated and the rest remained with the redirected work.
