### ISSUE TITLE
Merge UI should not allow merge if records have changed in the mean time

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6675]
When a super librarian clicks on the merge button the underlying code will re-fetch all the works/docs and if there are any edits (since) the UI will inform them to refresh

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
This should be somewhat fixed with how things are presently done (#6665)

**Comment by RayBB** [comment]
This is still an issue.

If someone does work on it here's an approach.

In MergeUI.vue's doMerge(), before calling do_merge(...):
1. Re-fetch the works via the existing fetchRecords(this.olids) (MergeTable.vue:89) — and editions if needed.
2. Compare each record's latest_revision (or last_modified) against the in-memory copies captured at page load (store a snapshot in data() when records() resolves).
3. If any differ, abort the merge, surface a toast/confirm: "These records have changed since you loaded this page. Please refresh." Keep the button disabled.

**Comment by WhoamiI00** [comment]
Hi @RayBB @jimchamp — can I take this one?

Had a look at master and it does still repro. MergeTable fetches the works once in `records()` (fetchRecords, MergeTable.vue:89) and everything after that (selection map, master pick, the merge payload) comes off that one snapshot. Then `doMerge()` in MergeUI.vue:125 just grabs `this.$refs.mergeTable.merge` and calls `do_merge(...)`. So nothing re-checks the records in between, and if someone edits one while your tab is sitting open, the merge goes through against the stale copy and their edit is gone. No warning either.

Was planning to follow @RayBB's outline above:

- stash each record's `latest_revision` when `records()` resolves
- re-fetch with `fetchRecords(this.olids)` at the top of `doMerge()` and compare
- if anything moved, bail before `do_merge` and tell them to refresh

So `MergeUI.vue` for the guard and the message, `MergeUI/MergeTable.vue` for the snapshot. Doesn't look like there's a test for either component right now, so I'd add one.

Few things I wasn't sure about:

- `latest_revision` or `last_modified`? Revision seemed like the safer thing to compare, but I don't know if anything bumps one without the other.
- Do the editions in `editions_to_move` need the same check, or are the works enough here?
- For the message, is OlToast fine or would you rather it be a hard confirm? And should the merge button stay dead until they refresh?

Happy to change the approach if I've got the wrong end of it.

**Comment by RayBB** [comment]
I think it seems like a reasonable approach. Revision seems like it's good to compare. I don't think we need to check the additions, and I think the button should stay dead until they refresh. 
Good luck!
