### ISSUE TITLE
Infinite redirects due to slug redirect code

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#787]
These two author records trigger infinite redirects:

https://openlibrary.org/authors/OL3942168A
https://openlibrary.org/authors/OL3535162A

They both have funky author "names" (the first is all ctrl/Zs and the second is a long string of number signs), so my speculation is that perhaps it's something to do with the redirect code which tries to add the name to the URL (which seems like wasted effort in the first place).

**Comment by hornc** [comment]
Another author record with infinite redirects (because the name / slug was '#')
OL2778519A, this one is now fixed. Had 3 books associated with, by different authors.

I deleted OL3942168A as it had no works.
OL3535162A had one work:
https://openlibrary.org/works/OL9529850W/Occupational_Safety_and_Health_Law_Handbook
According to Worldcat the author's name is 'Lesa L Byrum', so I changed it.

**Comment by hornc** [comment]
The authors above have all been fixed, the cause was bad data. If we find more of these are occurring we should add more protection in either data entry/save, or when generating redirects.

**Comment by tfmorris** [comment]
Here's a work with the same issue [?: The Question Book](https://openlibrary.org/works/OL2919929W).

The slug generation code needs to be fixed to generate valid URLs. Bonus points for getting rid of the wasteful redirect altogether.

**Comment by mekarpeles** [comment]
We confirmed that for "?: The Question Book", the "?" is causing infinite redirects.

The logic entry-point is here:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/processors/readableurls.py#L43

**Comment by mekarpeles** [comment]
Still potential issues in the readableurls logic, but the cases are now better known (documented in this thread) and the mentioned records have been fixed accordingly.

**Comment by tfmorris** [comment]
Wait, the code is still broken, it's super easy to fix (as documented by the "Good First Issue" tag), but the issue is being closed? What am I missing?
